# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to run the
# zipkin-elasticsearch container instead of the zipkin-mysql container.

version: '2'

services:
  # Run Elasticsearch instead of Cassandra
  storage:
    image: openzipkin/zipkin-elasticsearch:1.8.4
    container_name: elasticsearch
    ports:
      # http
      - 9200:9200
      # transport
      - 9300:9300

  # Switch storage type to Elasticsearch
  zipkin:
    image: openzipkin/zipkin:1.8.4
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch
  dependencies:
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
