apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "zipkin-query"
spec:
  replicas: 1
  selector:
    app: "zipkin-query"
  template:
    metadata:
      labels:
        app: "zipkin-query"
    spec:
      containers:
        - name: "query"
          image: "itszero/zipkin-query"
          ports:
            - containerPort: 9411
