apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "zipkin-web"
spec:
  replicas: 1
  selector:
    app: "zipkin-web"
  template:
    metadata:
      labels:
        app: "zipkin-web"
    spec:
      containers:
        - name: "web"
          image: "itszero/zipkin-web"
          ports:
            - containerPort: 8080
              name: "web"
            - containerPort: 9990
              name: "admin"
